server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luqianjiang/sprincloud-config.git
          search-paths:
            - springcloud-config
          skip-ssl-validation: true
          username: luqianjiang
          password: luqianjiang1234
        label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka



##rabbitmq相关配置,暴露bus刷新配置的端点 SpringCloud Bus动态刷新全局广播
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'